Fix a bug in compute_time_listings that would allow simultaneous runs
The cause of the bug is that if we fail to start because someone else has already started, we still delete their files.

From job-02 right now:

    write_permacache() # comment ("day", "week+
    write_permacache() # link ("day","week")
    write_permacache() # link ("day","week")
    write_permacache() # comment ("day", "week+
    write_permacache() # link ("month","year")
    write_permacache() # comment ("month", "ye+

diff --git a/scripts/compute_time_listings b/scripts/compute_time_listings
--- a/scripts/compute_time_listings
+++ b/scripts/compute_time_listings
@@ -49,7 +49,6 @@ DATA_DUMP=$TMPDIR/$THING_CLS-$INTERVAL-data.dump
 function clean_up {
     rm -f $THING_DUMP $DATA_DUMP
 }
-trap clean_up EXIT
 
 if [ -e $THING_DUMP ]; then
     echo cannot start because $THING_DUMP exists
@@ -58,6 +57,8 @@ if [ -e $THING_DUMP ]; then
 fi
 touch $THING_DUMP
 
+# since we're in charge of this run now, we have to clean up afterwards
+trap clean_up EXIT
 
 function run_query {
     psql -F"\t" -A -t -c "$1"
